manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: awkannan
      url-base: https://github.com/awkannan
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: awkannan
      revision: develop
      import: app/west.yml
    - name: zmk-gpio-behavior
      remote: awkannan
      revision: main
    - name: zmk-smart-rgbled-widget
      remote: awkannan
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
  self:
    path: config
